- name: Update setuptools
  pip: name=setuptools state=latest
  become: yes

- name: Install ndg-httpsclient so we can download couch
  pip: name="{{ item }}"
  become: yes
  with_items:
    - ndg-httpsclient

- name: Create couchdb2 dirs
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ couchdb_parent_srcs_dir }}"

- name: Install couchdb directly (bionic)
  become: yes
  block:
    - apt_key:
        url: https://couchdb.apache.org/repo/bintray-pubkey.asc
        state: present
    - apt_repository:
        repo: deb https://apache.bintray.com/couchdb-deb bionic main
        state: present
    - apt:
        name: couchdb
        state: present
  when: ansible_distribution_version == '18.04'
