---
language: python
python: "2.7"

env:
  global:
    - ANSIBLE_ROLES_PATH="~/.ansible/roles"
    - TRAVIS_TEST=1
    - GOROOT=~/go
    - PATH=$GOROOT/bin:$PATH
  matrix:
    - TEST=main
    - TEST=prove-deploy

matrix:
  fast_finish: true

before_install:
  # The next line exits out of the prove-deploy test if
  #   - the test is not running from a cron event
  #   - the last commit that was merged in doesn't contain [pv-test]
  - |
    if [[ $TEST = 'prove-deploy' && $TRAVIS_EVENT_TYPE != 'cron' ]] &&
      git log --pretty=format:'%s %b' -n1 HEAD^2 | grep -iv '\[pv-deploy\]'
    then
      exit 0
    fi
  # Make sure everything's up to date.
  - sudo apt-get clean
  - sudo apt-get update -qq

install:
  - "source control/init.sh"
  # Note: the installs must be done in the following order, otherwise the installation of commcare-cloud
  # tries to install from the commcare-cloud-bootstrap.egg_info directory
  - "pip install -e .[test]"
  - mkdir ~/.aws
  - touch ~/.aws/config
  - touch ~/.aws/credentials
  - touch ~/.ssh/commcarehq_testing.pem
  - |
    if [[ $TEST = 'prove-deploy' ]]
    then
      echo $VAULT_PASSWORD | ansible-vault --vault-password-file=/bin/cat decrypt .travis/secrets/.aws/config --output=~/.aws/config
      echo $VAULT_PASSWORD | ansible-vault --vault-password-file=/bin/cat decrypt .travis/secrets/.aws/credentials --output=~/.aws/credentials
      echo $VAULT_PASSWORD | ansible-vault --vault-password-file=/bin/cat decrypt .travis/secrets/.ssh/commcarehq_testing.pem --output=~/.ssh/commcarehq_testing.pem
      pip install -e commcare-cloud-bootstrap
    fi

  # install go, logstash-filter-verifier, logstash
  - wget https://dl.google.com/go/go1.12.4.linux-amd64.tar.gz
  - tar -xvf go1.12.2.linux-amd64.tar.gz
  - wget https://github.com/magnusbaeck/logstash-filter-verifier/releases/download/1.5.0/logstash-filter-verifier_1.5.0_linux_amd64.tar.gz
  - tar -xvf logstash-filter-verifier_1.5.0_linux_amd64.tar.gz
  - wget https://artifacts.elastic.co/downloads/logstash/logstash-7.0.0.tar.gz
  - tar -xvf logstash-7.0.0.tar.gz

script:
  - ".travis/tests.sh"

after_script:
  - "if [[ $TEST = 'prove-deploy' ]]; then commcare-cloud-bootstrap terminate hq-${TRAVIS_COMMIT}; fi"
