---
- name: Configure logstash
  become: yes
  template:
    src: "{{ item }}.j2"
    dest: "/etc/logstash/conf.d/{{ item }}"
  with_items:
    - templates/01-inputs.conf
    - templates/10-filters.conf
    - templates/90-outputs.conf
  notify:
    - restart logstash
