- name: Bootstrap Control
  hosts: "{{ target|default(control) }}"
  become: true
  gather_facts: true
  roles:
    - {role: users, tags: users}
    - {role: ssh, tags: ssh}
    - role: edit
    - {role: common_installs, tags: common_installs}
    - {role: ksplice, tags: ksplice}
    - {role: ansible-control, tags: ansible-control}
    - role: ansible-logrotate
      logrotate_scripts:
        - name: control_ansible
          path: /var/log/ansible.log
          options:
            - size 10M
            - rotate 5
            - missingok
            - compress
            - delaycompress
            - copytruncate
            - create
            - notifempty
