---
- src: git+https://github.com/andrewrothstein/ansible-couchdb-cluster.git
  version: 1d1558722c30e03cedb641e8bb2abf9ad5bc1fcd
  name: andrewrothstein.ansible-couchdb-cluster
- src: git+https://github.com/andrewrothstein/ansible-couchdb.git
  version: f0e026e73b8bf6f4ee5cc710f8fdbcdeb7418b2b
  name: andrewrothstein.couchdb
- src: git+https://github.com/debops-contrib/ansible-etckeeper.git
  version: 29c721de3df965ff355cbed242db813f70b811a2
  name: debops-contrib.etckeeper
- src: git+https://github.com/ANXS/tmpreaper.git
  version: 46f8e0b8b8f5732eecc68b08b5e0c392c418e3f3
  name: tmpreaper
- src: git+https://github.com/mrlesmithjr/ansible-squid.git
  version: 2d015170b7e4f28e4bc782af829f340974efaf2d
  name: squid
- src: git+https://github.com/nickhammond/ansible-logrotate.git
  version: e7a498
  name: ansible-logrotate
- src: DavidWittman.redis
  version: 1.2.5
